services:
  web:
    image: php:8.2-apache
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/vendor
      - ./.env:/var/www/.env
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./apache.conf:/etc/apache2/conf-available/apache.conf
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && a2enconf apache.conf && apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soprando_cartucho
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
